# -*- coding: utf-8 -*-
"""Chapter 9 — Quantum Error Correction and Fault Tolerance."""
from math import log10
from engine import (p, eq, box, code, table, ul, ol, cr_qtext, stack_question,
                    stack_qtext, figure, cite, sources, line_chart, circuit_svg,
                    flow_svg, interactive, C, SERIF, MONO)

S1 = (
    p("Quantum error correction has to defeat three objections that make it look impossible.")
    + ol([
        "<strong>No-cloning</strong> forbids the classical trick of storing three copies of the "
        "state. Resolution: encode into an entangled subspace rather than duplicating.",
        "<strong>Errors are continuous.</strong> A qubit can rotate by an arbitrary angle, so "
        "there seem to be uncountably many errors to correct. Resolution: the syndrome "
        "measurement <em>discretises</em> them (§3).",
        "<strong>Measurement destroys superposition.</strong> Resolution: measure only the "
        "<em>syndrome</em> — operators that commute with the logical information and reveal the "
        "error without revealing the encoded state.",
    ])
    + box('ex', 'The three-qubit bit-flip code',
          "Encode \\(\\alpha|0\\rangle+\\beta|1\\rangle\\mapsto\\alpha|000\\rangle+\\beta|111\\rangle\\). "
          "Measure the commuting observables \\(Z_1Z_2\\) and \\(Z_2Z_3\\): their outcomes "
          "(the <em>syndrome</em>) identify which single qubit flipped, without revealing "
          "\\(\\alpha,\\beta\\). Apply the corresponding \\(X\\) and the state is restored. "
          "The code corrects any single \\(X\\) error but no \\(Z\\) error — "
          "\\(Z_1\\) acts as a logical \\(Z\\) and is invisible to the syndrome.")
    + p("Concatenating the bit-flip code with its Hadamard-conjugated phase-flip counterpart "
        "gives Shor's nine-qubit code, the first code able to correct an arbitrary single-qubit "
        "error.")
)

S2 = (
    box('thm', 'Knill–Laflamme conditions',
        "Let \\(\\mathcal C\\subseteq\\mathcal H\\) be a code with projector \\(P\\), and let "
        "\\(\\{E_a\\}\\) be a set of errors. There exists a recovery channel correcting every "
        "\\(E_a\\) if and only if "
        "\\(P E_a^{\\dagger}E_b P=c_{ab}P\\) for a Hermitian matrix \\(c_{ab}\\) of scalars.")
    + p("Interpretation: distinct errors must map the code space to <em>distinguishable</em> "
        "subspaces (\\(a\\ne b\\) off-diagonal), and no error may reveal information about the "
        "encoded state (the right-hand side is proportional to \\(P\\), independent of which "
        "codeword). Degenerate codes are those where \\(c\\) is singular — several errors act "
        "identically, which is allowed and sometimes advantageous.")
    + box('prop', 'Discretisation of errors',
          "If a code corrects the Pauli set \\(\\{I,X_i,Y_i,Z_i\\}\\) for all \\(i\\), it corrects "
          "<em>every</em> single-qubit error. Proof: any single-qubit channel has Kraus operators "
          "expandable in the Pauli basis, \\(E_a=\\sum_\\mu e_{a\\mu}\\sigma_\\mu\\); linearity of "
          "the Knill–Laflamme conditions in \\(E\\) then extends correction to the whole span. "
          "\\(\\blacksquare\\)")
    + p("This is the crucial point. There is no need to correct a continuum: the syndrome "
        "measurement projects a small continuous rotation onto 'no error' or 'a specific Pauli "
        "error', and only the discrete case must be handled. Analogue errors become digital.")
    + p("Parameters are written \\([[n,k,d]]\\): \\(n\\) physical qubits encode \\(k\\) logical "
        "ones with distance \\(d\\), correcting \\(t=\\lfloor(d-1)/2\\rfloor\\) arbitrary "
        "single-qubit errors. The quantum Singleton bound gives \\(n-k\\ge2(d-1)\\); the "
        "smallest code correcting one arbitrary error is the perfect \\([[5,1,3]]\\) code, "
        "saturating the quantum Hamming bound.")
)

S3 = (
    p("The Pauli group \\(\\mathcal P_n\\) consists of the \\(n\\)-fold tensor products of "
      "\\(\\{I,X,Y,Z\\}\\) with phases \\(\\{\\pm1,\\pm i\\}\\). Any two elements either commute or "
      "anticommute.")
    + box('def', 'Stabilizer code',
          "Let \\(S\\le\\mathcal P_n\\) be an abelian subgroup with \\(-I\\notin S\\), generated by "
          "\\(n-k\\) independent elements. The code space is the joint \\(+1\\) eigenspace "
          "\\(\\mathcal C=\\{|\\psi\\rangle:g|\\psi\\rangle=|\\psi\\rangle\\ \\forall g\\in S\\}\\), of "
          "dimension \\(2^{k}\\). The syndrome of an error \\(E\\) is the vector of commutation "
          "relations with the generators: \\(E\\) is detectable iff it anticommutes with at least "
          "one generator. The distance is the minimum weight of an element of "
          "\\(N(S)\\setminus S\\).")
    + table(['Code', 'Parameters', 'Notes'],
            [['Bit flip', '\\([[3,1,1]]\\)', 'Stabilizers \\(Z_1Z_2, Z_2Z_3\\); X errors only'],
             ['Shor', '\\([[9,1,3]]\\)', 'First code for an arbitrary single error; concatenated'],
             ['Steane', '\\([[7,1,3]]\\)', 'CSS from the Hamming [7,4,3] code; transversal Clifford'],
             ['Perfect code', '\\([[5,1,3]]\\)', 'Smallest distance-3 code; saturates the Hamming bound'],
             ['Surface code', '\\([[d^{2},1,d]]\\)', 'Local 4-body checks on a 2-D lattice; ~1% threshold'],
             ['Colour code', '\\([[\\Theta(d^{2}),1,d]]\\)', 'Transversal Clifford in 2-D, higher weight checks']])
    + box('thm', 'Gottesman–Knill',
          "A circuit consisting of state preparation in the computational basis, Clifford gates "
          "\\(\\{H,S,\\text{CNOT}\\}\\) and computational-basis measurement can be simulated "
          "classically in \\(O(n^{2})\\) time per gate, by tracking how the stabilizer generators "
          "transform in the Heisenberg picture. Entanglement is therefore not sufficient for "
          "quantum advantage; the non-Clifford resource is.")
    + p("<strong>CSS codes</strong> are stabilizer codes whose generators split into pure-\\(X\\) and "
        "pure-\\(Z\\) types, built from a pair of classical linear codes with "
        "\\(C_2\\subseteq C_1\\). They correct bit and phase errors independently, which makes "
        "decoding a classical problem — a large part of why the surface code is practical.")
)

S4 = (
    p("A code alone is not enough: the encoding, syndrome extraction, correction and logical "
      "gates are themselves built from faulty components. Fault tolerance requires that a single "
      "physical fault cannot propagate into an uncorrectable logical error — typically ensured "
      "by <em>transversal</em> gate constructions, in which each physical qubit of one block "
      "interacts with at most one qubit of another.")
    + box('thm', 'Threshold theorem (Aharonov–Ben-Or; Kitaev; Knill–Laflamme–Zurek 1996–97)',
          "There exists a constant \\(p_{\\text{th}}>0\\) such that, for any physical error rate "
          "\\(p<p_{\\text{th}}\\) in a local stochastic noise model, an arbitrary quantum circuit "
          "of size \\(T\\) can be simulated to accuracy \\(\\varepsilon\\) using "
          "\\(O\\big(T\\,\\mathrm{polylog}(T/\\varepsilon)\\big)\\) faulty gates. Concatenation "
          "gives logical error \\(p_L\\sim p_{\\text{th}}(p/p_{\\text{th}})^{2^{\\ell}}\\) at level "
          "\\(\\ell\\); for a distance-\\(d\\) surface code, "
          "\\(p_L\\approx A(p/p_{\\text{th}})^{\\lfloor(d+1)/2\\rfloor}\\).")
    + box('thm', 'Eastin–Knill',
          "No quantum error-detecting code admits a universal set of transversal logical gates. "
          "Some gate must be implemented non-transversally — in the surface code, the "
          "\\(T\\) gate, via <strong>magic state distillation</strong>: many noisy copies of "
          "\\(|T\\rangle=(|0\\rangle+e^{i\\pi/4}|1\\rangle)/\\sqrt2\\) are purified with Clifford "
          "operations and consumed by gate teleportation. This is the dominant cost of "
          "fault-tolerant computation, and the reason Chapter 3 insisted on T-count.")
    + p("The surface code is currently the leading architecture: 4-body checks between "
        "nearest neighbours on a 2-D lattice, a threshold near \\(1\\%\\), and efficient "
        "minimum-weight-perfect-matching decoding. Its cost is the overhead — roughly "
        "\\(d^{2}\\) physical qubits per logical qubit, so \\(10^{3}\\)–\\(10^{4}\\) physical per "
        "logical at realistic error rates.")
    + box('note', 'State of the art',
          "Google's 2023 and 2024 experiments demonstrated a distance-7 surface-code logical "
          "qubit below threshold, with the logical error rate roughly halving for each increase "
          "of \\(d\\) by 2 — the first clear demonstration that scaling the code helps. "
          "Neutral-atom and ion-trap platforms have shown logical entangling gates and "
          "transversal operations on dozens of logical qubits. Useful fault-tolerant computation "
          "still requires several more orders of magnitude in qubit count and cycle fidelity.")
)

S5 = (
    code('''import numpy as np
from itertools import product

# --- symplectic representation: a Pauli on n qubits is (x|z) in F_2^{2n} ---
def commutes(p1, p2, n):
    """Symplectic product: 0 = commute, 1 = anticommute."""
    x1, z1 = p1[:n], p1[n:]
    x2, z2 = p2[:n], p2[n:]
    return int((np.dot(x1, z2) + np.dot(z1, x2)) % 2) == 0

def syndrome(error, stabilizers, n):
    return tuple(0 if commutes(error, g, n) else 1 for g in stabilizers)

# 3-qubit bit-flip code: stabilizers Z1Z2, Z2Z3  (x-part 0, z-part as shown)
n = 3
S = [np.array([0,0,0, 1,1,0]), np.array([0,0,0, 0,1,1])]
for i in range(3):                       # single X errors
    e = np.zeros(6, dtype=int); e[i] = 1
    print(i, syndrome(e, S, n))          # 0 (1,0)   1 (1,1)   2 (0,1)''',
         'Symplectic (binary) representation: syndromes are linear-algebra over GF(2)')
    + p("Working in the symplectic representation is the practical way to handle stabilizer "
        "codes: a Pauli becomes a binary vector \\((x|z)\\in\\mathbb F_2^{2n}\\), commutation "
        "becomes the symplectic form \\(x_1\\cdot z_2+z_1\\cdot x_2\\), and syndrome extraction "
        "and decoding become linear algebra over \\(\\mathbb F_2\\). Phases are tracked "
        "separately when needed.")
)

# =============================== figures, citations and added commentary =====
BITFLIP_CIRCUIT = circuit_svg(
    5,
    [[('c', 0, 1, 'X')],
     [('c', 0, 2, 'X')],
     [('lab', 1, 'noise acts here')],
     [('c', 0, 3, 'X'), ('c', 1, 4, 'X')],
     [('c', 1, 3, 'X'), ('c', 2, 4, 'X')],
     [('m', 3), ('m', 4)]],
    wire_labels=['α|0⟩+β|1⟩', '|0⟩', '|0⟩', '|0⟩ anc', '|0⟩ anc'], width=640,
    title='Three-qubit bit-flip code: encoding, then syndrome extraction onto two ancillas')

SURFACE_SVG = f'''
<rect x="0" y="0" width="680" height="330" fill="#ffffff"/>
<text x="340" y="20" font-family="{SERIF}" font-size="13" fill="{C['accent']}" text-anchor="middle" font-weight="bold">Surface code, distance 5: local four-body checks on a square lattice</text>
{''.join(
    f'<rect x="{60 + 52*c}" y="{44 + 52*r}" width="52" height="52" fill="'
    + ('#ecfeff' if (r + c) % 2 == 0 else '#fefce8') + '" stroke="#cbd5e1" stroke-width="1"/>'
    for r in range(4) for c in range(4))}
{''.join(
    f'<text x="{86 + 52*c}" y="{75 + 52*r}" font-family="{SERIF}" font-size="13" '
    f'fill="' + ('#026573' if (r + c) % 2 == 0 else '#92400e') + '" text-anchor="middle" '
    'font-weight="bold">' + ('Z' if (r + c) % 2 == 0 else 'X') + '</text>'
    for r in range(4) for c in range(4))}
{''.join(
    f'<circle cx="{60 + 52*c}" cy="{44 + 52*r}" r="6" fill="#0f172a"/>'
    for r in range(5) for c in range(5))}
<text x="340" y="298" font-family="{SERIF}" font-size="12.5" fill="{C['body']}" text-anchor="middle">Black dots are data qubits; each shaded plaquette is a weight-4 stabilizer measured every cycle</text>
<text x="340" y="318" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="middle">A d&#215;d patch encodes one logical qubit with distance d, using d&#178; data qubits and d&#178;&#8722;1 ancillas</text>
<line x1="60" y1="44" x2="60" y2="252" stroke="#dc2626" stroke-width="3"/>
<text x="112" y="272" font-family="{SERIF}" font-size="12" fill="#dc2626" text-anchor="middle">red: a logical operator, weight d</text>
<text x="392" y="60" font-family="{SERIF}" font-size="12.5" fill="#026573" text-anchor="start" font-weight="bold">Z-type check: detects phase flips</text>
<text x="392" y="82" font-family="{SERIF}" font-size="12.5" fill="#92400e" text-anchor="start" font-weight="bold">X-type check: detects bit flips</text>
<text x="392" y="112" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">Checks of the two types overlap in</text>
<text x="392" y="130" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">exactly two qubits, so they commute.</text>
<text x="392" y="158" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">Errors appear as pairs of flipped</text>
<text x="392" y="176" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">checks; decoding is minimum-weight</text>
<text x="392" y="194" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">perfect matching on those defects.</text>
<text x="392" y="222" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">A logical error requires a chain of</text>
<text x="392" y="240" font-family="{SERIF}" font-size="12.5" fill="{C['muted']}" text-anchor="start">at least d errors spanning the patch.</text>
'''

_pp = [10 ** (-3 + 0.05 * k) for k in range(0, 41)]      # 1e-3 .. 1e-1
PTH = 1e-2
THRESH = line_chart(
    [dict(label='d = 3', xs=[log10(q) for q in _pp],
          ys=[log10(0.1 * (q / PTH) ** 2) for q in _pp], color='#026573'),
     dict(label='d = 5', xs=[log10(q) for q in _pp],
          ys=[log10(0.1 * (q / PTH) ** 3) for q in _pp], color='#c9a227'),
     dict(label='d = 7', xs=[log10(q) for q in _pp],
          ys=[log10(0.1 * (q / PTH) ** 4) for q in _pp], color='#9333ea'),
     dict(label='d = 11', xs=[log10(q) for q in _pp],
          ys=[log10(0.1 * (q / PTH) ** 6) for q in _pp], color='#dc2626'),
     dict(label='no encoding (logical = physical)', xs=[log10(q) for q in _pp],
          ys=[log10(q) for q in _pp], color='#94a3b8', dash='5 4')],
    xlim=(-3, -1), ylim=(-14, 0), xticks=[-3,-2.5,-2,-1.5,-1],
    yticks=[-14,-10,-6,-2,0], xlabel='log₁₀ (physical error rate p)',
    ylabel='log₁₀ (logical error rate)',
    vlines=[(log10(PTH), 'threshold p_th = 1%', '#475569')], height=340)

JS_THRESH = """
  var b = JXG.JSXGraph.initBoard('ch9thr', {boundingbox: [-3.35, 1.2, -0.75, -15.5],
      axis: false, showCopyright: false, showNavigation: false});
  var dS = b.create('slider', [[-3.25, 0.4], [-2.15, 0.4], [3, 7, 25]],
      {name: 'distance d', snapWidth: 2, strokeColor: '#026573'});
  var pth = -2;
  b.create('line', [[-3.3, 0], [-0.8, 0]], {strokeColor: '#0f172a', strokeWidth: 1.4,
      straightFirst: false, straightLast: false, fixed: true});
  b.create('line', [[-3.3, 0], [-3.3, -15]], {strokeColor: '#0f172a', strokeWidth: 1.4,
      straightFirst: false, straightLast: false, fixed: true});
  b.create('line', [[pth, 1], [pth, -15]], {strokeColor: '#475569', dash: 2,
      straightFirst: false, straightLast: false, fixed: true});
  b.create('text', [pth + 0.03, -14.6, 'threshold  p = 1%'], {fontSize: 12, strokeColor: '#475569'});
  b.create('functiongraph', [function (lp) { return lp; }, -3.3, -0.8],
      {strokeColor: '#94a3b8', strokeWidth: 1.6, dash: 2});
  b.create('functiongraph', [function (lp) {
      var d = Math.round(dS.Value());
      var e = Math.floor((d + 1) / 2);
      return Math.log(0.1) / Math.LN10 + e * (lp - pth);
  }, -3.3, -0.8], {strokeColor: '#026573', strokeWidth: 2.8});
  b.create('text', [-3.3, -15.2, function () {
      var d = Math.round(dS.Value());
      var e = Math.floor((d + 1) / 2);
      var lp = Math.log(1e-3) / Math.LN10;
      var lL = Math.log(0.1) / Math.LN10 + e * (lp - pth);
      return 'd = ' + d + ':  ' + (d * d) + ' data qubits,  at p = 10^-3 the logical rate is 10^' +
             lL.toFixed(1);
  }], {fontSize: 13.5, strokeColor: '#0f172a'});
  b.create('text', [-2.4, 0.75, 'horizontal: log&#8321;&#8320; p   vertical: log&#8321;&#8320; p_L'],
      {fontSize: 12, strokeColor: '#475569'});
"""

S1 = S1 + figure(
    '9.1',
    'The three-qubit bit-flip code in full. The first two CNOTs spread the logical information over '
    'three physical qubits without ever copying the amplitudes α and β — no-cloning is respected '
    'because the encoded state is entangled, not duplicated. The last four CNOTs compute the parities '
    'Z₁Z₂ and Z₂Z₃ onto two ancillas, which are then measured. The measurement learns which qubit '
    'flipped and nothing whatsoever about α and β.',
    BITFLIP_CIRCUIT, width=640, height=328) + p(
    "The syndrome extraction is the conceptual heart of the subject and repays slow reading. "
    "Measuring \\(Z_1Z_2\\) is not the same as measuring \\(Z_1\\) and \\(Z_2\\): the product "
    "commutes with the logical operators, so it has no information about the encoded state, while "
    "each factor separately would collapse the superposition entirely. Error correction is "
    "possible precisely because the algebra of observables is rich enough to contain operators that "
    "see the error but not the data" + cite('4,10') + ".") + sources(
    'The three-qubit codes and the general strategy: Shor' + cite('1') + ', Gottesman\'s '
    'introduction' + cite('10') + '.')

S2 = S2 + sources(
    'Necessary and sufficient conditions: Knill &amp; Laflamme' + cite('3') + '; the discretisation '
    'argument and code parameters: Nielsen &amp; Chuang ch. 10, Gottesman' + cite('4') + '.')

S3 = S3 + figure(
    '9.2',
    'The surface code, the architecture most large-scale proposals are built on. Data qubits sit at '
    'lattice sites and every plaquette carries a weight-four stabilizer, alternating between the two '
    'types so that any two checks overlap in an even number of qubits and therefore commute. All '
    'operations are between nearest neighbours, which is exactly what solid-state hardware can do. '
    'A logical operator is a chain crossing the patch, so it has weight d and the code distance is d.',
    SURFACE_SVG, height=330) + p(
    "Two features explain why this code has displaced the algebraically prettier alternatives. "
    "First, locality: every check involves four neighbouring qubits, so no long-range coupling is "
    "needed, and the syndrome can be extracted by a fixed short circuit repeated indefinitely"
    + cite('5,6') + ". Second, decodability: because the code is of CSS type, bit and phase errors "
    "decouple, and each type reduces to a matching problem on the graph of flipped checks that can "
    "be solved in near-linear time by minimum-weight perfect matching. The price is the overhead — "
    "\\(d^{2}\\) data qubits plus a comparable number of ancillas for one logical qubit — and the "
    "Eastin–Knill obstruction discussed next." + cite('8')) + sources(
    'Stabilizer formalism: Gottesman' + cite('4') + '; the toric/surface code: Kitaev' + cite('5')
    + '; the engineering account: Fowler et al.' + cite('6') + '.')

S4 = S4 + figure(
    '9.3',
    'The threshold, seen directly. Each curve gives the logical error rate of a distance-d surface '
    'code as a function of the physical error rate, both logarithmic. To the left of the threshold '
    'the curves fall below the grey no-encoding line and steepen with d — adding qubits helps, '
    'exponentially. To the right they rise above it: encoding makes matters worse, because the '
    'error-correction circuitry itself introduces more faults than it removes. Everything in '
    'fault-tolerant engineering is an effort to stay on the left.',
    THRESH, height=340) + interactive(
    '9.4', 'ch9thr',
    'Increase the code distance and watch the slope steepen. The two regimes meet at the threshold: '
    'below it, every extra two units of distance buys another factor of p/p_th in logical error; '
    'above it, larger codes are strictly worse. Read off the distance needed for a logical error '
    'rate of 10⁻¹² at a physical rate of 10⁻³ — and then multiply d² by the number of logical qubits '
    'an algorithm needs to see where the twenty-million-qubit estimates of Chapter 7 come from.',
    JS_THRESH, aspect='16/9', max_width=660,
    hint='drag the distance slider.') + p(
    "The experimental milestone that mattered was crossing from the right to the left of that "
    "divide. Google's 2024 experiment compared distance-3, -5 and -7 surface-code memories on the "
    "same device and found the logical error rate falling by roughly a factor of two for each "
    "increase of \\(d\\) by two, which is the signature of operating below threshold" + cite('9')
    + ". That is a qualitative change: before it, larger codes made things worse, and no amount of "
    "engineering could have been extrapolated to a useful machine. It does not, however, close the "
    "gap — the demonstrated logical error rates are near \\(10^{-3}\\), and the algorithms of "
    "Chapter 7 need something closer to \\(10^{-12}\\)." ) + sources(
    'Threshold theorem: Kitaev' + cite('5') + ' and Fowler et al. for the surface-code constants'
    + cite('6') + '; magic state distillation: Bravyi &amp; Kitaev' + cite('7') + '; '
    'Eastin–Knill' + cite('8') + '; the below-threshold experiment' + cite('9') + '.')

REFS = [
    dict(authors="P. W. Shor", title="Scheme for reducing decoherence in quantum computer memory",
         venue="Physical Review A 52, R2493", year="1995",
         note="The nine-qubit code; the paper that started the field."),
    dict(authors="A. M. Steane", title="Error correcting codes in quantum theory",
         venue="Physical Review Letters 77, 793", year="1996",
         note="The [[7,1,3]] CSS code."),
    dict(authors="E. Knill and R. Laflamme", title="Theory of quantum error-correcting codes",
         venue="Physical Review A 55, 900", year="1997",
         link="https://arxiv.org/abs/quant-ph/9604034",
         note="The necessary and sufficient conditions of §2."),
    dict(authors="D. Gottesman", title="Stabilizer Codes and Quantum Error Correction",
         venue="PhD thesis, Caltech", year="1997",
         link="https://arxiv.org/abs/quant-ph/9705052",
         note="The definitive account of the stabilizer formalism used in §3."),
    dict(authors="A. Yu. Kitaev", title="Fault-tolerant quantum computation by anyons",
         venue="Annals of Physics 303(1), 2–30", year="2003",
         link="https://arxiv.org/abs/quant-ph/9707021",
         note="The toric/surface code."),
    dict(authors="A. G. Fowler, M. Mariantoni, J. M. Martinis and A. N. Cleland",
         title="Surface codes: towards practical large-scale quantum computation",
         venue="Physical Review A 86, 032324", year="2012",
         link="https://arxiv.org/abs/1208.0928",
         note="The standard engineering reference for surface-code architectures."),
    dict(authors="S. Bravyi and A. Kitaev",
         title="Universal quantum computation with ideal Clifford gates and noisy ancillas",
         venue="Physical Review A 71, 022316", year="2005",
         link="https://arxiv.org/abs/quant-ph/0403025",
         note="Magic state distillation."),
    dict(authors="B. Eastin and E. Knill",
         title="Restrictions on transversal encoded quantum gate sets",
         venue="Physical Review Letters 102, 110502", year="2009",
         link="https://arxiv.org/abs/0811.4262",
         note="No code has a universal transversal gate set."),
    dict(authors="Google Quantum AI and Collaborators",
         title="Quantum error correction below the surface code threshold",
         venue="Nature 638, 920–926", year="2025",
         link="https://arxiv.org/abs/2408.13687",
         note="Distance-7 below-threshold logical qubit; the experimental state of §4."),
    dict(authors="D. Gottesman", title="An introduction to quantum error correction and fault-tolerant quantum computation",
         venue="arXiv:0904.2557", year="2009",
         link="https://arxiv.org/abs/0904.2557",
         note="The best single-document introduction at this level."),
]

CR = [
    dict(
        name='C9.Q1 — The three-qubit bit-flip code, end to end',
        qtext=cr_qtext('C9.Q1', 'Encode, corrupt, diagnose, correct',
                       "\\(\\alpha|0\\rangle+\\beta|1\\rangle\\mapsto\\alpha|000\\rangle+\\beta|111\\rangle\\), "
                       "with syndrome \\((Z_1Z_2, Z_2Z_3)\\).",
                       "Write <code>encode3(alpha, beta)</code> returning the 8-dimensional "
                       "encoded state; <code>apply_x(state, q)</code> applying \\(X\\) to qubit "
                       "\\(q\\) (0 = most significant); <code>syndrome3(state)</code> returning "
                       "the tuple of \\(\\pm1\\) eigenvalues of \\(Z_1Z_2\\) and \\(Z_2Z_3\\) as "
                       "<code>int</code>s; and <code>correct3(state)</code> returning the "
                       "corrected state.",
                       "syndrome3(no error) -> (1, 1)\n"
                       "syndrome3(X on qubit 0) -> (-1, 1)\n"
                       "syndrome3(X on qubit 1) -> (-1, -1)\n"
                       "syndrome3(X on qubit 2) -> (1, -1)"),
        answer='''import numpy as np

X = np.array([[0, 1], [1, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)

def _embed(U, q, n=3):
    ops = [I2] * n
    ops[q] = U
    out = np.array([[1.0 + 0j]])
    for o in ops:
        out = np.kron(out, o)
    return out

def encode3(alpha, beta):
    v = np.zeros(8, dtype=complex)
    v[0] = alpha
    v[7] = beta
    return v

def apply_x(state, q):
    return _embed(X, q) @ np.asarray(state, dtype=complex)

def syndrome3(state):
    state = np.asarray(state, dtype=complex)
    S1 = _embed(Z, 0) @ _embed(Z, 1)
    S2 = _embed(Z, 1) @ _embed(Z, 2)
    return tuple(int(round(float(np.real(np.vdot(state, S @ state))))) for S in (S1, S2))

def correct3(state):
    s = syndrome3(state)
    table = {(1, 1): None, (-1, 1): 0, (-1, -1): 1, (1, -1): 2}
    q = table[s]
    return np.asarray(state, dtype=complex) if q is None else apply_x(state, q)
''',
        preload='''import numpy as np

def encode3(alpha, beta):
    ...

def apply_x(state, q):
    ...

def syndrome3(state):
    ...

def correct3(state):
    ...
''',
        tests=[
            {'code': 'import numpy as np\nv = encode3(0.6, 0.8)\nprint(syndrome3(v))\n',
             'expected': '(1, 1)\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': 'import numpy as np\nv = encode3(0.6, 0.8)\n'
                     'print([syndrome3(apply_x(v, q)) for q in range(3)])\n',
             'expected': '[(-1, 1), (-1, -1), (1, -1)]\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': 'import numpy as np\nv = encode3(0.6, 0.8)\n'
                     'print(all(np.allclose(correct3(apply_x(v, q)), v) for q in range(3)))\n',
             'expected': 'True\n', 'useasexample': '0', 'display': 'SHOW'},
            {'code': 'import numpy as np\nv = encode3(1/np.sqrt(2), 1j/np.sqrt(2))\n'
                     'print(np.allclose(correct3(v), v))\n',
             'expected': 'True\n', 'useasexample': '0', 'display': 'HIDE'},
            {'code': 'import numpy as np\nv = encode3(0.6, 0.8)\n'
                     'w = apply_x(apply_x(v, 0), 1)\n'
                     'print(syndrome3(w), np.allclose(correct3(w), v))\n',
             'expected': '(1, -1) False\n', 'useasexample': '0', 'display': 'HIDE'},
        ]),
    dict(
        name='C9.Q2 — Stabilizer codes in the symplectic representation',
        qtext=cr_qtext('C9.Q2', 'Syndromes as linear algebra over GF(2)',
                       "A Pauli on \\(n\\) qubits is a binary vector \\((x|z)\\); two Paulis "
                       "commute iff \\(x_1\\!\\cdot\\!z_2+z_1\\!\\cdot\\!x_2=0 \\bmod 2\\).",
                       "Write <code>commutes(p1, p2, n)</code> returning a <code>bool</code>; "
                       "<code>syndrome(error, stabilizers, n)</code> returning a tuple of bits; "
                       "<code>is_valid_stabilizer_group(gens, n)</code> checking that all "
                       "generators pairwise commute; and "
                       "<code>weight(pauli, n)</code> returning the number of qubits on which "
                       "the Pauli acts non-trivially.",
                       "Steane code X-generators: IIIXXXX, IXXIIXX, XIXIXIX\n"
                       "and the mirrored Z-generators."),
        answer='''import numpy as np

def commutes(p1, p2, n):
    p1 = np.asarray(p1, dtype=int)
    p2 = np.asarray(p2, dtype=int)
    s = (np.dot(p1[:n], p2[n:]) + np.dot(p1[n:], p2[:n])) % 2
    return bool(s == 0)

def syndrome(error, stabilizers, n):
    return tuple(0 if commutes(error, g, n) else 1 for g in stabilizers)

def is_valid_stabilizer_group(gens, n):
    for i in range(len(gens)):
        for j in range(i + 1, len(gens)):
            if not commutes(gens[i], gens[j], n):
                return False
    return True

def weight(pauli, n):
    pauli = np.asarray(pauli, dtype=int)
    return int(sum(1 for i in range(n) if pauli[i] or pauli[n + i]))
''',
        preload='''import numpy as np

def commutes(p1, p2, n):
    ...

def syndrome(error, stabilizers, n):
    ...

def is_valid_stabilizer_group(gens, n):
    ...

def weight(pauli, n):
    ...
''',
        tests=[
            {'code': 'import numpy as np\nn=1\nXp=[1,0]; Zp=[0,1]\n'
                     'print(commutes(Xp, Zp, n), commutes(Xp, Xp, n))\n',
             'expected': 'False True\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': '''import numpy as np
n = 3
S = [[0,0,0, 1,1,0], [0,0,0, 0,1,1]]
errs = [[1,0,0, 0,0,0], [0,1,0, 0,0,0], [0,0,1, 0,0,0]]
print([syndrome(e, S, n) for e in errs])
''',
             'expected': '[(1, 0), (1, 1), (0, 1)]\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': '''import numpy as np
n = 7
Xg = [[0,0,0,1,1,1,1] + [0]*7, [0,1,1,0,0,1,1] + [0]*7, [1,0,1,0,1,0,1] + [0]*7]
Zg = [[0]*7 + [0,0,0,1,1,1,1], [0]*7 + [0,1,1,0,0,1,1], [0]*7 + [1,0,1,0,1,0,1]]
print(is_valid_stabilizer_group(Xg + Zg, n))
''',
             'expected': 'True\n', 'useasexample': '0', 'display': 'SHOW'},
            {'code': '''import numpy as np
n = 7
Xg = [[0,0,0,1,1,1,1] + [0]*7, [0,1,1,0,0,1,1] + [0]*7, [1,0,1,0,1,0,1] + [0]*7]
Zg = [[0]*7 + [0,0,0,1,1,1,1], [0]*7 + [0,1,1,0,0,1,1], [0]*7 + [1,0,1,0,1,0,1]]
S = Xg + Zg
seen = set()
for i in range(7):
    e = [0]*14; e[i] = 1                    # X error on qubit i
    seen.add(syndrome(e, S, n))
print(len(seen), (0,)*6 in seen)
''',
             'expected': '7 False\n', 'useasexample': '0', 'display': 'HIDE'},
            {'code': 'print(weight([1,0,1, 0,1,0], 3), weight([0,0,0, 0,0,0], 3))\n',
             'expected': '3 0\n', 'useasexample': '0', 'display': 'HIDE'},
        ]),
    dict(
        name='C9.Q3 — Verifying the Knill–Laflamme conditions',
        qtext=cr_qtext('C9.Q3', 'Is this code correcting?',
                       "\\(P E_a^{\\dagger}E_b P=c_{ab}P\\) is necessary and sufficient. Checking "
                       "it numerically for a small code is a direct matrix computation.",
                       "Write <code>code_projector(basis)</code> returning \\(P=\\sum_i "
                       "|c_i\\rangle\\langle c_i|\\) for an orthonormal list of codewords; and "
                       "<code>knill_laflamme(P, errors, tol=1e-9)</code> returning "
                       "<code>True</code> iff \\(PE_a^{\\dagger}E_bP\\) is a scalar multiple of "
                       "\\(P\\) for every pair.",
                       "3-qubit bit-flip code with errors {I, X1, X2, X3} -> True\n"
                       "same code with a Z error added                    -> False"),
        answer='''import numpy as np

def code_projector(basis):
    P = None
    for c in basis:
        c = np.asarray(c, dtype=complex).ravel()
        c = c / np.linalg.norm(c)
        term = np.outer(c, c.conj())
        P = term if P is None else P + term
    return P

def knill_laflamme(P, errors, tol=1e-9):
    P = np.asarray(P, dtype=complex)
    nrm = np.real(np.trace(P @ P))
    for Ea in errors:
        for Eb in errors:
            M = P @ np.asarray(Ea, dtype=complex).conj().T @ np.asarray(Eb, dtype=complex) @ P
            c = np.trace(P @ M) / nrm
            if not np.allclose(M, c * P, atol=tol):
                return False
    return True
''',
        preload='''import numpy as np

def code_projector(basis):
    ...

def knill_laflamme(P, errors, tol=1e-9):
    ...
''',
        tests=[
            {'code': '''import numpy as np
c0 = np.zeros(8, dtype=complex); c0[0] = 1
c1 = np.zeros(8, dtype=complex); c1[7] = 1
P = code_projector([c0, c1])
print(np.allclose(P @ P, P), round(float(np.real(np.trace(P))), 6))
''',
             'expected': 'True 2.0\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': '''import numpy as np
X = np.array([[0,1],[1,0]], dtype=complex); I2 = np.eye(2, dtype=complex)
def emb(U, q):
    ops = [I2]*3; ops[q] = U
    out = np.array([[1.0+0j]])
    for o in ops: out = np.kron(out, o)
    return out
c0 = np.zeros(8, dtype=complex); c0[0] = 1
c1 = np.zeros(8, dtype=complex); c1[7] = 1
P = code_projector([c0, c1])
errs = [np.eye(8, dtype=complex)] + [emb(X, q) for q in range(3)]
print(knill_laflamme(P, errs))
''',
             'expected': 'True\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': '''import numpy as np
X = np.array([[0,1],[1,0]], dtype=complex)
Z = np.array([[1,0],[0,-1]], dtype=complex); I2 = np.eye(2, dtype=complex)
def emb(U, q):
    ops = [I2]*3; ops[q] = U
    out = np.array([[1.0+0j]])
    for o in ops: out = np.kron(out, o)
    return out
c0 = np.zeros(8, dtype=complex); c0[0] = 1
c1 = np.zeros(8, dtype=complex); c1[7] = 1
P = code_projector([c0, c1])
errs = [np.eye(8, dtype=complex)] + [emb(X, q) for q in range(3)] + [emb(Z, 0)]
print(knill_laflamme(P, errs))
''',
             'expected': 'False\n', 'useasexample': '0', 'display': 'SHOW'},
            {'code': '''import numpy as np
X = np.array([[0,1],[1,0]], dtype=complex); I2 = np.eye(2, dtype=complex)
def emb(U, q):
    ops = [I2]*3; ops[q] = U
    out = np.array([[1.0+0j]])
    for o in ops: out = np.kron(out, o)
    return out
c0 = np.zeros(8, dtype=complex); c0[0] = 1
c1 = np.zeros(8, dtype=complex); c1[7] = 1
P = code_projector([c0, c1])
errs = [np.eye(8, dtype=complex), emb(X, 0), emb(X, 1), emb(X, 2), emb(X,0) @ emb(X,1)]
print(knill_laflamme(P, errs))
''',
             'expected': 'False\n', 'useasexample': '0', 'display': 'HIDE'},
            {'code': '''import numpy as np
c0 = np.array([1, 0], dtype=complex)
P = code_projector([c0])
print(knill_laflamme(P, [np.eye(2, dtype=complex)]))
''',
             'expected': 'True\n', 'useasexample': '0', 'display': 'HIDE'},
        ]),
    dict(
        name='C9.Q4 — Thresholds, concatenation and overhead',
        qtext=cr_qtext('C9.Q4', 'When does error correction actually help?',
                       "A distance-\\(d\\) code suppresses errors as "
                       "\\(p_L\\approx A(p/p_{\\text{th}})^{\\lfloor(d+1)/2\\rfloor}\\); concatenating "
                       "\\(\\ell\\) levels of a distance-3 code gives "
                       "\\(p_L\\approx p_{\\text{th}}(p/p_{\\text{th}})^{2^{\\ell}}\\). Below "
                       "threshold, more qubits help; above it, they hurt.",
                       "Write <code>logical_error_surface(p, p_th, d, A=0.1)</code>; "
                       "<code>logical_error_concat(p, p_th, levels)</code>; and "
                       "<code>min_distance_for(p, p_th, target, A=0.1)</code> returning the "
                       "smallest odd \\(d\\ge3\\) with "
                       "<code>logical_error_surface(p, p_th, d, A) <= target</code> "
                       "(search up to \\(d=101\\), return <code>None</code> if none works). "
                       "Round the two error rates to 12 decimals.",
                       "logical_error_surface(1e-3, 1e-2, 3) -> 0.1 * (0.1)^2 = 0.001\n"
                       "min_distance_for(1e-3, 1e-2, 1e-12) -> 21"),
        answer='''import numpy as np

def logical_error_surface(p, p_th, d, A=0.1):
    return round(float(A * (p / p_th) ** ((d + 1) // 2)), 12)

def logical_error_concat(p, p_th, levels):
    return round(float(p_th * (p / p_th) ** (2 ** levels)), 12)

def min_distance_for(p, p_th, target, A=0.1):
    if p >= p_th:
        return None
    for d in range(3, 102, 2):
        if logical_error_surface(p, p_th, d, A) <= target:
            return d
    return None
''',
        preload='''import numpy as np

def logical_error_surface(p, p_th, d, A=0.1):
    ...

def logical_error_concat(p, p_th, levels):
    ...

def min_distance_for(p, p_th, target, A=0.1):
    ...
''',
        tests=[
            {'code': 'print(logical_error_surface(1e-3, 1e-2, 3))\n',
             'expected': '0.001\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': 'print(min_distance_for(1e-3, 1e-2, 1e-12))\n',
             'expected': '21\n', 'useasexample': '1', 'display': 'SHOW'},
            {'code': 'print(logical_error_concat(1e-3, 1e-2, 0), logical_error_concat(1e-3, 1e-2, 2))\n',
             'expected': '0.001 1e-06\n', 'useasexample': '0', 'display': 'SHOW'},
            {'code': 'print(min_distance_for(2e-2, 1e-2, 1e-12))\n',
             'expected': 'None\n', 'useasexample': '0', 'display': 'HIDE'},
            {'code': 'print(logical_error_surface(1e-3, 1e-2, 5) < logical_error_surface(1e-3, 1e-2, 3))\n',
             'expected': 'True\n', 'useasexample': '0', 'display': 'HIDE'},
        ]),
]

ST = [
    stack_question(
        name='C9.S1 — Code parameters and bounds',
        questiontext=stack_qtext(
            'C9.S1', 'Reading [[n,k,d]]',
            r'<p>A stabilizer code has parameters \([[n,k,d]]\) with \(d={@d@}\).</p>'
            r'<p>(a) Give the number of arbitrary single-qubit errors it can correct, in terms of '
            r'<code>d</code> (use <code>floor</code>).</p>'
            r'<p>\(t=\) [[input:ans1]] [[validation:ans1]]</p>'
            r'<p>(b) Give the number of independent stabilizer generators, in terms of '
            r'<code>n</code> and <code>k</code>.</p>'
            r'<p>[[input:ans2]] [[validation:ans2]]</p>'
            r'<p>(c) The quantum Singleton bound reads \(n-k\ge \alpha(d-1)\). Give \(\alpha\).</p>'
            r'<p>\(\alpha=\) [[input:ans3]] [[validation:ans3]]</p>'),
        generalfeedback=(
            r'<p>(a) \(t=\lfloor (d-1)/2\rfloor\). For \(d={@d@}\) this is \({@ta1@}\). '
            r'A distance-\(d\) code <em>detects</em> \(d-1\) errors but only <em>corrects</em> half '
            r'that many, since two correctable errors must map the code space to distinguishable '
            r'subspaces.</p>'
            r'<p>(b) The code space is the joint \(+1\) eigenspace of \(n-k\) independent '
            r'generators, each halving the dimension: \(2^{n}/2^{n-k}=2^{k}\).</p>'
            r'<p>(c) \(\alpha=2\): the quantum Singleton bound is \(n-k\ge2(d-1)\), twice the '
            r'classical one, because both bit and phase errors must be corrected. Codes meeting it '
            r'with equality are called quantum MDS; the \([[5,1,3]]\) code is an example.</p>'),
        questionvariables='d : rand_with_step(3,9,2);\nta1 : floor((d-1)/2);\nta2 : n-k;\nta3 : 2;',
        questionnote='d={@d@}, t={@ta1@}',
        parts=[
            dict(input='ans1', prt='prt1', tans='ta1', boxsize=14, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb=r'<p>Two errors of weight \(t\) must be distinguishable, so \(2t<d\).</p>'),
            dict(input='ans2', prt='prt2', tans='ta2', boxsize=10, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb=r'<p>Each independent generator halves the dimension of the eigenspace.</p>'),
            dict(input='ans3', prt='prt3', tans='ta3', boxsize=6, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb='<p>The quantum bound is twice the classical Singleton bound.</p>')]),
    stack_question(
        name='C9.S2 — Below and above threshold',
        questiontext=stack_qtext(
            'C9.S2', 'The threshold theorem, quantitatively',
            r'<p>For a distance-\(d\) surface code, \(p_L\approx A\,(p/p_{\mathrm{th}})^{(d+1)/2}\) '
            r'with \(d\) odd.</p>'
            r'<p>(a) Give \(p_L\) for \(A=1\), \(p_{\mathrm{th}}=10^{-2}\), \(p=10^{-3}\) and '
            r'\(d={@d@}\) (exact expression, no decimals).</p>'
            r'<p>\(p_L=\) [[input:ans1]] [[validation:ans1]]</p>'
            r'<p>(b) Concatenating \(\ell\) levels of a distance-3 code gives '
            r'\(p_L=p_{\mathrm{th}}(p/p_{\mathrm{th}})^{e(\ell)}\). Give the exponent \(e(\ell)\) '
            r'in terms of <code>l</code>.</p>'
            r'<p>\(e(\ell)=\) [[input:ans2]] [[validation:ans2]]</p>'
            r'<p>(c) Give the number of physical qubits per logical qubit for a distance-\(d\) '
            r'surface code (leading order, in terms of <code>d</code>).</p>'
            r'<p>[[input:ans3]] [[validation:ans3]]</p>'),
        generalfeedback=(
            r'<p>(a) The exponent is \((d+1)/2\); with \(p/p_{\mathrm{th}}=10^{-1}\) this gives '
            r'\(p_L=10^{-(d+1)/2}={@ta1@}\).</p>'
            r'<p>(b) Each concatenation level squares the ratio, so \(e(\ell)=2^{\ell}\): the '
            r'suppression is doubly exponential in the number of levels, and only '
            r'\(\mathrm{polylog}\) levels are needed for any target — the content of the threshold '
            r'theorem.</p>'
            r'<p>(c) \(d^{2}\) (or \(2d^{2}-1\) counting ancillas, depending on the layout). At '
            r'\(p/p_{\mathrm{th}}=1/10\) and a target of \(10^{-12}\), \(d\approx23\), so roughly '
            r'\(500\)–\(1000\) physical qubits per logical qubit — before accounting for magic '
            r'state factories, which typically dominate the total footprint.</p>'),
        questionvariables='d : rand_with_step(3,11,2);\nta1 : 10^(-(d+1)/2);\nta2 : 2^l;\nta3 : d^2;',
        questionnote='d={@d@}, pL={@ta1@}',
        parts=[
            dict(input='ans1', prt='prt1', tans='ta1', boxsize=16, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb=r'<p>Substitute \(p/p_{\mathrm{th}}=10^{-1}\) and the given \(d\).</p>'),
            dict(input='ans2', prt='prt2', tans='ta2', boxsize=10, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb='<p>Each level squares the previous ratio.</p>'),
            dict(input='ans3', prt='prt3', tans='ta3', boxsize=8, value='0.3333333',
                 truefb='<p>Correct.</p>',
                 falsefb='<p>The surface code is a 2-D lattice of side \\(d\\).</p>')]),
    stack_question(
        name='C9.S3 — Stabilizer arithmetic and the Steane code',
        questiontext=stack_qtext(
            'C9.S3', 'Counting states and syndromes',
            r'<p>The Steane code is \([[7,1,3]]\).</p>'
            r'<p>(a) Give the number of independent stabilizer generators.</p>'
            r'<p>[[input:ans1]] [[validation:ans1]]</p>'
            r'<p>(b) Give the number of distinct non-trivial syndromes available, and compare with '
            r'the number of weight-1 Pauli errors on 7 qubits. Enter the ordered pair '
            r'<code>[syndromes, errors]</code>.</p>'
            r'<p>[[input:ans2]] [[validation:ans2]]</p>'
            r'<p>(c) For a general \([[n,1,3]]\) code, the quantum Hamming bound requires '
            r'\(2^{n-1}\ge 1+3n\). Give the smallest \(n\) satisfying it.</p>'
            r'<p>\(n=\) [[input:ans3]] [[validation:ans3]]</p>'),
        generalfeedback=(
            r'<p>(a) \(n-k=7-1=6\).</p>'
            r'<p>(b) Six generators give \(2^{6}=64\) syndromes, of which \(63\) are non-trivial. '
            r'There are \(3\times7=21\) weight-1 Pauli errors, so the syndromes are far from '
            r'exhausted — the Steane code is not perfect. (It is, however, CSS and admits '
            r'transversal Clifford gates, which matters more in practice.)</p>'
            r'<p>(c) \(2^{n-1}\ge 1+3n\): at \(n=5\), \(16\ge16\) holds with equality, so \(n=5\). '
            r'That is the \([[5,1,3]]\) perfect code, which saturates the bound — every non-trivial '
            r'syndrome corresponds to exactly one correctable error.</p>'),
        questionvariables='ta1 : 6;\nta2 : [63,21];\nta3 : 5;',
        questionnote='6 generators, [63,21], n=5',
        parts=[
            dict(input='ans1', prt='prt1', tans='ta1', boxsize=6, value='0.3333333',
                 truefb='<p>Correct.</p>', falsefb='<p>It is \\(n-k\\).</p>'),
            dict(input='ans2', prt='prt2', tans='ta2', boxsize=16, value='0.3333333',
                 forbidfloat=0,
                 truefb='<p>Correct — the code is not perfect.</p>',
                 falsefb=r'<p>\(2^{6}-1\) non-trivial syndromes; \(3n\) weight-1 Paulis.</p>'),
            dict(input='ans3', prt='prt3', tans='ta3', boxsize=6, value='0.3333333',
                 truefb=r'<p>Correct — the \([[5,1,3]]\) perfect code.</p>',
                 falsefb=r'<p>Test \(n=3,4,5\) in \(2^{n-1}\ge1+3n\).</p>')]),
]

CHAPTER = dict(
    no=9, slug='error-correction-fault-tolerance',
    title='Quantum Error Correction and Fault Tolerance',
    subtitle='Why QEC is possible at all, the Knill–Laflamme conditions and error discretisation, '
             'the stabilizer and CSS formalism, the surface code, the threshold theorem, '
             'Eastin–Knill and magic state distillation.',
    prereq='Chapters 1–5 (Pauli algebra, channels, noise models); Chapter 3 for Clifford gates.',
    objectives=[
        'Explain how encoding into a subspace and syndrome measurement evade no-cloning and collapse.',
        'State and apply the Knill–Laflamme conditions, and prove that Pauli correction suffices.',
        'Construct stabilizer codes, compute syndromes in the symplectic representation, and read [[n,k,d]].',
        'Describe CSS and surface codes and why they are the practical choice.',
        'State the threshold theorem and estimate logical error rates and qubit overheads.',
        'Explain Eastin–Knill and why magic state distillation dominates fault-tolerant cost.',
    ],
    sections=[
        ('Three objections and their resolutions', S1),
        ('The Knill–Laflamme conditions and error discretisation', S2),
        ('The stabilizer formalism', S3),
        ('Fault tolerance, thresholds and magic states', S4),
        ('Numerical practice', S5),
    ],
    summary="Quantum information is protected by encoding it into an entangled subspace whose "
            "stabilizer syndrome reveals errors without revealing the state. The Knill–Laflamme "
            "conditions characterise correctable error sets, and linearity reduces the continuum "
            "of physical errors to a finite Pauli set. Stabilizer and CSS codes make syndrome "
            "extraction and decoding linear algebra over GF(2); the surface code turns this into "
            "a 2-D nearest-neighbour architecture with a ~1% threshold. The threshold theorem "
            "guarantees arbitrary-accuracy computation below that rate, at polylogarithmic "
            "overhead in theory and \\(10^{3}\\)–\\(10^{4}\\) physical qubits per logical qubit in "
            "practice, dominated by magic state distillation for non-Clifford gates.",
    references=REFS, coderunner=CR, stack=ST,
)
